### ISSUE TITLE
Update RStudio download link

### ISSUE THREAD

**Issue by Aariq** [eliocamp/reproducibility-with-r#24]
On Day 0 the link to https://www.rstudio.com/products/rstudio/download/ redirects to https://posit.co/products/, which is not exactly the right place to download RStudio.  I suggest updating to https://posit.co/download/rstudio-desktop/

(part of JOSE review here: https://github.com/openjournals/jose-reviews/issues/260)

**Comment by eliocamp** [comment]
Huh. Seems Posit should fix this obviously wrong redirect 😜.
