### ISSUE TITLE
RStudio & markdown bug resolved—update text?

### ISSUE THREAD

**Issue by Aariq** [eliocamp/reproducibility-with-r#28]
I noticed that the [bug ](https://github.com/rstudio/rstudio/issues/9861)you link to in [this section](https://reproducibility.rocks/materials/day3/01-renv/#using-renv-in-your-project) is now closed.  Probably not urgent, but next time you revise this text, you might remove this part.

**Comment by eliocamp** [comment]
Thanks. I've confirmed that the bug not longer happens with the current RStudio version. I kept the message in case someone's using an old RStudio version.
